<?php
// $Id$

/**
 * @file
 * Installation functionality for Mollom testing module.
 */

/**
 * Implements hook_schema().
 */
function mollom_test_schema() {
  $schema['mollom_test'] = array(
    'description' => 'Stores testing data for Mollom test form.',
    'fields' => array(
      'mid' => array('type' => 'serial', 'not null' => TRUE,
        'description' => 'Primary key: Unique mollom_test entity ID.',
      ),
      'body' => array('type' => 'text', 'not null' => TRUE,
        'description' => 'The body field of mollom_test_form().',
      ),
    ),
    'primary key' => array('mid'),
  );
  return $schema;
}

